# Generated by Django 4.2.4 on 2024-03-01 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=500000)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(choices=[('silver', 'Silver'), ('platinum', 'Platinum'), ('gold', 'Gold')], default='platinum', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='Links/images')),
                ('media', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50)),
                ('visting', models.CharField(max_length=50)),
                ('audience', models.CharField(max_length=150)),
                ('action', models.URLField(blank=True)),
                ('cost', models.FloatField(max_length=1000000, null=True)),
                ('category', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Links.category')),
            ],
        ),
    ]
