# Generated by Django 4.2.4 on 2024-03-11 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='links',
            name='category',
        ),
        migrations.AddField(
            model_name='links',
            name='category',
            field=models.ManyToManyField(default=False, to='Links.category'),
        ),
    ]
